<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Overview</strong>' => '',
    'Are you really sure? All existing category page assignments will be removed!' => '',
    'Categories' => '',
    'Category' => '',
    'Invalid category!' => '',
    'Is category' => '',
    'Page list' => '',
    'Pages in this category' => '',
    'Pages without category' => '',
    'Show all {count} pages.' => '',
    '<strong>Confirm</strong> page deleting' => '<strong>Potvrdi</strong> brisanje stranice',
    '<strong>Confirm</strong> page reverting' => '<strong>Potvrdi</strong> vraćanje stranice',
    '<strong>Overview</strong> of all pages' => '<strong>Pregled</strong> svih stranica',
    '<strong>Page</strong> history' => '<strong>Povijest</strong> stranice',
    '<strong>Wiki</strong> Module' => '<strong>Wiki</strong> modul',
    'Adds a wiki to this space.' => 'Dodaje wiki u taj prostor.',
    'Adds a wiki to your profile.' => 'Dodaje wiki u vaš profil',
    'Back to page' => 'Povratak na stranicu.',
    'Cancel' => 'Poništi.',
    'Delete' => 'Obriši.',
    'Do you really want to delete this page?' => 'Želite li stvarno obrisati ovu stranicu?',
    'Do you really want to revert this page?' => 'Želite li stvarno vratiti ovu stranicu?',
    'Edit page' => 'Uredi stranicu',
    'Edited at' => 'Uređeno u',
    'Go back' => 'Idi natrag',
    'Invalid character in page title!' => 'Nevažeći simbol u naslovu stranice!',
    'Is homepage' => 'Početna stranica',
    'Let\'s go!' => 'Idemo!',
    'Main page' => 'Glavna stranica',
    'New page' => 'Nova stranica',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'Nijedna stranica još nije izrađena. Stoga je na vama. <br> Napravite prvu stranicu sada.',
    'Overview' => 'Pregled',
    'Page History' => 'Povijest stranice',
    'Page creation disabled!' => 'Kreiranje stranice onemogućeno!',
    'Page not editable!' => 'Stranica nije za uređivanje!',
    'Page not found.' => 'Stranica nije pronađena.',
    'Page title already in use!' => 'Naslov stranice već u upotrebi!',
    'Permalink' => 'Permalink',
    'Permission denied. You have no administration rights.' => 'Dopuštenje je odbijeno. Nemate prava administracije.',
    'Permission denied. You have no rights to view the history.' => 'Dopuštenje je odbijeno. Nemate prava za prikaz povijesti.',
    'Protected' => 'Zaštićeno',
    'Revert' => 'Vrati',
    'Revert not possible. Already latest revision!' => 'Vraćanje nije moguće. Već je zadnja revizija!',
    'Revert this' => 'Vrati ovo',
    'View' => 'Vidi',
    'Wiki' => 'Wiki',
    'You need to be member of the space "%space_name%" to access this wiki page!' => 'Morate biti član prostora "%space_name%" da pristupite wiki stranici!',
    'by' => 'od',
];
