<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> page deleting' => '<strong>Vahavista</strong> sivun poisto',
    '<strong>Confirm</strong> page reverting' => '<strong>Vahvista</strong> sivun palautus',
    '<strong>Overview</strong> of all pages' => '<strong>Sivut</strong>',
    '<strong>Page</strong> history' => '<strong>Sivun</strong> historia',
    '<strong>Wiki</strong> Module' => '<strong>Blogi</strong> Laajennus',
    'Adds a wiki to this space.' => 'Lisää blogi tälle sivulle',
    'Adds a wiki to your profile.' => 'Lisää blogi profiilisi',
    'Back to page' => 'Takaisin',
    'Do you really want to delete this page?' => 'Haluatko todella poistaa tämän sivun?',
    'Do you really want to revert this page?' => 'Halutako todella palauttaa tämän sivun?',
    'Edit page' => 'Muokka sivua',
    'Edited at' => 'Muokannut',
    'Go back' => 'Takaisin',
    'Invalid character in page title!' => '',
    'Is homepage' => 'Etusivu',
    'Let\'s go!' => '',
    'Main page' => 'Pääsivu',
    'New page' => 'Uusi sivu',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => '',
    'Overview' => 'Sivut',
    'Page History' => 'Sivun historia',
    'Page creation disabled!' => 'Sivun muokkaus ei ole käytetävissä',
    'Page not editable!' => 'Sivu ei ole muokattavissa',
    'Page not found.' => 'Sivua ei löydy.',
    'Page title already in use!' => '',
    'Permalink' => 'Linkki',
    'Permission denied. You have no administration rights.' => '',
    'Permission denied. You have no rights to view the history.' => '',
    'Protected' => 'Suojattu',
    'Revert' => 'Palauta',
    'Revert not possible. Already latest revision!' => '',
    'Revert this' => 'Palauta tämä',
    'View' => 'Näkymä',
    'Wiki' => 'Blogi',
    'You need to be member of the space "%space_name%" to access this wiki page!' => '',
    'by' => 'luonut',
    'Cancel' => 'Peruuta',
    'Delete' => 'Poista',
];
