<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Overview</strong>' => '',
    'Are you really sure? All existing category page assignments will be removed!' => '',
    'Categories' => '',
    'Category' => '',
    'Invalid category!' => '',
    'Is category' => '',
    'Is homepage' => '',
    'Page creation disabled!' => '',
    'Page list' => '',
    'Page not editable!' => '',
    'Page not found.' => '',
    'Pages in this category' => '',
    'Pages without category' => '',
    'Permission denied. You have no administration rights.' => '',
    'Permission denied. You have no rights to view the history.' => '',
    'Protected' => '',
    'Revert not possible. Already latest revision!' => '',
    'Show all {count} pages.' => '',
    'You need to be member of the space "%space_name%" to access this wiki page!' => '',
    '<strong>Confirm</strong> page deleting' => '<strong>Подтвердите</strong> удаление страницы',
    '<strong>Confirm</strong> page reverting' => '<strong>Подтвердите</strong> восстановление страницы',
    '<strong>Overview</strong> of all pages' => '<strong>Обзор</strong> всех страниц',
    '<strong>Page</strong> history' => '<strong>История</strong> страницы',
    '<strong>Wiki</strong> Module' => '<strong>Модуль</strong> Wiki',
    'Adds a wiki to this space.' => 'Добавляет wiki в это пространство.',
    'Adds a wiki to your profile.' => 'Добавляет wiki в ваш профиль.',
    'Back to page' => 'Назад к странице',
    'Cancel' => 'Отменить',
    'Delete' => 'Удалить',
    'Do you really want to delete this page?' => 'Вы действительно хотите удалить эту страницу?',
    'Do you really want to revert this page?' => 'Вы действительно хотите восстановить эту страницу?',
    'Edit page' => 'Редактировать страницу',
    'Edited at' => 'Отредактировано',
    'Go back' => 'Вернуться',
    'Invalid character in page title!' => 'Неверный символ в заголовке страницы!',
    'Let\'s go!' => 'Вперед!',
    'Main page' => 'Главная страница',
    'New page' => 'Новая страница',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'Созданных страниц пока нет.  <br>Создайте первую страницу сейчас.',
    'Overview' => 'Обзор',
    'Page History' => 'История страницы',
    'Page title already in use!' => 'Название страницы уже используется!',
    'Permalink' => 'Постоянная ссылка',
    'Revert' => 'Восстановить',
    'Revert this' => 'Восстановить это',
    'View' => 'Просмотр',
    'Wiki' => 'Wiki',
    'by' => 'от',
];
