<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> page deleting' => '',
    '<strong>Confirm</strong> page reverting' => '',
    '<strong>Overview</strong> of all pages' => '',
    '<strong>Page</strong> history' => '',
    '<strong>Wiki</strong> Module' => '',
    'Adds a wiki to this space.' => '',
    'Adds a wiki to your profile.' => '',
    'Back to page' => '',
    'Cancel' => '',
    'Delete' => '',
    'Do you really want to delete this page?' => '',
    'Do you really want to revert this page?' => '',
    'Edit page' => '',
    'Edited at' => '',
    'Go back' => '',
    'Invalid character in page title!' => '',
    'Let\'s go!' => '',
    'Main page' => '',
    'New page' => '',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => '',
    'Overview' => '',
    'Page History' => '',
    'Page title already in use!' => '',
    'Permalink' => '',
    'Revert' => '',
    'Revert this' => '',
    'View' => '',
    'Wiki' => '',
    'by' => '',
];
