<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Overview</strong>' => '',
    'Are you really sure? All existing category page assignments will be removed!' => '',
    'Categories' => '',
    'Category' => '',
    'Invalid category!' => '',
    'Is category' => '',
    'Is homepage' => '',
    'Page creation disabled!' => '',
    'Page list' => '',
    'Page not editable!' => '',
    'Page not found.' => '',
    'Pages in this category' => '',
    'Pages without category' => '',
    'Permission denied. You have no administration rights.' => '',
    'Permission denied. You have no rights to view the history.' => '',
    'Protected' => '',
    'Revert not possible. Already latest revision!' => '',
    'Show all {count} pages.' => '',
    'You need to be member of the space "%space_name%" to access this wiki page!' => '',
    '<strong>Confirm</strong> page deleting' => '<strong>Confirmar</strong> la eliminación de la página',
    '<strong>Confirm</strong> page reverting' => '<strong>Confirmar</strong> reversión de la página',
    '<strong>Overview</strong> of all pages' => '<strong>Resumen</strong> de todas las páginas',
    '<strong>Page</strong> history' => '<strong>Historial</strong> de la página',
    '<strong>Wiki</strong> Module' => 'Módulo <strong>Wiki</strong>',
    'Adds a wiki to this space.' => 'Añade una wiki a este espacio.',
    'Adds a wiki to your profile.' => 'Añade una wiki a tu perfil.',
    'Back to page' => 'Volver a la página',
    'Cancel' => 'Cancelar',
    'Delete' => 'Borrar',
    'Do you really want to delete this page?' => '¿Seguro que quieres eliminar esta página?',
    'Do you really want to revert this page?' => '¿Seguro que quieres revertir los cambios de esta página?',
    'Edit page' => 'Editar página',
    'Edited at' => 'Editado a',
    'Go back' => 'Ir atrás',
    'Invalid character in page title!' => '¡Caracter inválido en el título de la página!',
    'Let\'s go!' => '¡Vamos allá!',
    'Main page' => 'Página principal',
    'New page' => 'Nueva página',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'No hay páginas creadas todavía. <br>Crea la primera página ahora',
    'Overview' => 'Resumen',
    'Page History' => 'Historial de la página',
    'Page title already in use!' => '¡Título de la página ya en uso!',
    'Permalink' => 'Permalink',
    'Revert' => 'Revertir',
    'Revert this' => 'Revertir esto',
    'View' => 'Ver',
    'Wiki' => 'Wiki',
    'by' => 'por',
];
