<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Permalink' => '',
    '<strong>Confirm</strong> page deleting' => '<strong>Confirmer</strong> la suppression de la page',
    '<strong>Confirm</strong> page reverting' => '<strong>Confirmer</strong> le retour à une version précédente',
    '<strong>Overview</strong> of all pages' => '<strong>Aperçu</strong> des pages',
    '<strong>Page</strong> history' => '<strong>Historique</strong> de la page',
    '<strong>Wiki</strong> Module' => 'Module <strong>Wiki</strong>',
    'Adds a wiki to this space.' => 'Ajouter un Wiki à cet espace.',
    'Adds a wiki to your profile.' => 'Ajouter un Wiki à votre profil.',
    'Back to page' => 'Revenir à la page',
    'Cancel' => 'Annuler',
    'Delete' => 'Supprimer',
    'Do you really want to delete this page?' => 'Souhaitez-vous vraiment supprimer cette page ?',
    'Do you really want to revert this page?' => 'Souhaitez-vous vraiment restaurer cette page ?',
    'Edit page' => 'Modifier la page',
    'Edited at' => 'Modifié le',
    'Go back' => 'Retour',
    'Invalid character in page title!' => 'Caractère invalide dans le titre de la page !',
    'Let\'s go!' => 'Allons-y !',
    'Main page' => 'Page principale',
    'New page' => 'Nouvelle page',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'Aucune page pour l\'instant.<br>Créez la première page maintenant.',
    'Overview' => 'Vue d\'ensemble',
    'Page History' => 'Historique',
    'Page title already in use!' => 'Ce titre est déjà utilisé',
    'Revert' => 'Restaurer',
    'Revert this' => 'Restaurer ceci',
    'View' => 'Voir',
    'Wiki' => 'Wiki',
    'by' => 'par',
];
