<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Permalink' => '',
    '<strong>Confirm</strong> page deleting' => '<strong>Confirme</strong> apagar a página',
    '<strong>Confirm</strong> page reverting' => '<strong>Confirme</strong> reverter a página',
    '<strong>Overview</strong> of all pages' => '<strong>Visão geral</strong> de todas as páginas',
    '<strong>Page</strong> history' => 'Histórico da <strongi>Página</strong>',
    '<strong>Wiki</strong> Module' => 'Módulo <strong>Wiki</strong>',
    'Adds a wiki to this space.' => 'Adicionar uma wiki para este espaço',
    'Adds a wiki to your profile.' => 'Adicionar uma wiki para este perfil.',
    'Back to page' => 'Voltar para a página',
    'Cancel' => 'Cancelar',
    'Delete' => 'Apagar',
    'Do you really want to delete this page?' => 'Você realmente quer apagar esta página?',
    'Do you really want to revert this page?' => 'Você realmente quer reverter esta página?',
    'Edit page' => 'Editar página',
    'Edited at' => 'Editado em',
    'Go back' => 'Voltar',
    'Invalid character in page title!' => 'Caractere inválido no título da página!',
    'Let\'s go!' => 'Vamos lá!',
    'Main page' => 'Página principal',
    'New page' => 'Nova página',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'Não existem páginas criadas ainda. Então é com você.<br> Crie a primeira página agora.',
    'Overview' => 'Visão global',
    'Page History' => 'Histórico da página',
    'Page title already in use!' => 'Título da página já está em uso!',
    'Revert' => 'Reverter',
    'Revert this' => 'Reverter este',
    'View' => 'Visualizar',
    'Wiki' => 'Wiki',
    'by' => 'por',
];
