<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Overview</strong>' => '',
    'Are you really sure? All existing category page assignments will be removed!' => '',
    'Categories' => '',
    'Category' => '',
    'Invalid category!' => '',
    'Is category' => '',
    'Page list' => '',
    'Pages in this category' => '',
    'Pages without category' => '',
    'Show all {count} pages.' => '',
    '<strong>Confirm</strong> page deleting' => '<strong>Bevestig</strong> pagina verwijderen',
    '<strong>Confirm</strong> page reverting' => '<strong>Bevestig</strong> pagina terugzetten',
    '<strong>Overview</strong> of all pages' => '<strong>Overzicht</strong> van alle pagina\'s',
    '<strong>Page</strong> history' => '<strong>Pagina</strong> geschiedenis',
    '<strong>Wiki</strong> Module' => '<strong>Wiki</strong> Module',
    'Adds a wiki to this space.' => 'Voegt een wiki toe aan deze ruimte.',
    'Adds a wiki to your profile.' => 'Voegt een wiki toe aan je profiel.',
    'Back to page' => 'Terug naar pagina',
    'Cancel' => 'Annuleren',
    'Delete' => 'Verwijder',
    'Do you really want to delete this page?' => 'Ben je zeker dat je deze pagina wilt verwijderen?',
    'Do you really want to revert this page?' => 'Ben je zeker dat je deze pagina wilt terugzetten?',
    'Edit page' => 'Bewerk',
    'Edited at' => 'Bewerkt op',
    'Go back' => 'Ga terug',
    'Invalid character in page title!' => 'Ongeldig teken in paginatitel!',
    'Is homepage' => 'Is startpagina',
    'Let\'s go!' => 'Nieuwe pagina',
    'Main page' => 'Hoofdpagina',
    'New page' => 'Nieuw',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'Er zijn momenteel nog geen pagina\'s.',
    'Overview' => 'Overzicht',
    'Page History' => 'Historie',
    'Page creation disabled!' => 'Maken nieuwe pagina is uitgeschakeld.',
    'Page not editable!' => 'Pagina is niet aangepasbaar.',
    'Page not found.' => 'Pagina niet gevonden.',
    'Page title already in use!' => 'Paginatitel reeds in gebruik',
    'Permalink' => 'Permalink
',
    'Permission denied. You have no administration rights.' => 'Toegang geweigerd. U hebt geen beheerdersrechten.',
    'Permission denied. You have no rights to view the history.' => 'Toegang geweigerd. U hebt geen rechten om de historie te bekijken.',
    'Protected' => 'Beschermd',
    'Revert' => 'Terugzetten',
    'Revert not possible. Already latest revision!' => 'Terugdraaien is niet mogelijk. Dit is al de laatste herziening.',
    'Revert this' => 'Terugzetten',
    'View' => 'Toon',
    'Wiki' => 'Wiki',
    'You need to be member of the space "%space_name%" to access this wiki page!' => 'U moet lid zijn van de ruimte "%space_name%" te zijn om toegang te krijgen tot deze wiki pagina!',
    'by' => 'door',
];
