<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Is homepage' => '',
    'Page creation disabled!' => '',
    'Page not editable!' => '',
    'Page not found.' => '',
    'Permission denied. You have no administration rights.' => '',
    'Permission denied. You have no rights to view the history.' => '',
    'Protected' => '',
    'Revert not possible. Already latest revision!' => '',
    'You need to be member of the space "%space_name%" to access this wiki page!' => '',
    '<strong>Confirm</strong> page deleting' => '<strong>Potvrďte</strong> smazání stránky',
    '<strong>Confirm</strong> page reverting' => '<strong>Potvrďte</strong> obnovu stránky',
    '<strong>Overview</strong> of all pages' => '<strong>Přehled</strong> všech stránek',
    '<strong>Page</strong> history' => '<strong>Historie</strong> úprav stránky',
    '<strong>Wiki</strong> Module' => '<strong>Wiki</strong> stránky',
    'Adds a wiki to this space.' => 'Přidá wiki stránku do prostoru.',
    'Adds a wiki to your profile.' => 'Přidá wiki stránku do vašeho profilu.',
    'Back to page' => 'Zpět na stránku',
    'Cancel' => 'Zrušit',
    'Delete' => 'Smazat',
    'Do you really want to delete this page?' => 'Opravdu chcete smazat tuto stránku?',
    'Do you really want to revert this page?' => 'Opravdu chcete obnovit tuto stránku?',
    'Edit page' => 'Změnit stránku',
    'Edited at' => 'Změněno',
    'Go back' => 'Zpět',
    'Invalid character in page title!' => 'V titulku stránky se nachází nepovolený znak.',
    'Let\'s go!' => 'Vytvořit',
    'Main page' => 'Hlavní stránka',
    'New page' => 'Nová stránka',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'Zatím nebyla vytvořena žádná stránka.',
    'Overview' => 'Přehled',
    'Page History' => 'Historie úprav stránky',
    'Page title already in use!' => 'Tento titulek již používá jiná stránka.',
    'Permalink' => 'Trvalý odkaz',
    'Revert' => 'Obnovit',
    'Revert this' => 'Obnovit',
    'View' => 'Zobrazit',
    'Wiki' => 'Wiki',
    'by' => 'uživatelem',
];
