<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Overview</strong>' => '',
    'Are you really sure? All existing category page assignments will be removed!' => '',
    'Categories' => '',
    'Category' => '',
    'Invalid category!' => '',
    'Is category' => '',
    'Page list' => '',
    'Pages in this category' => '',
    'Pages without category' => '',
    'Show all {count} pages.' => '',
    '<strong>Confirm</strong> page deleting' => 'Löschen der Seite <strong>bestätigen</strong> ',
    '<strong>Confirm</strong> page reverting' => 'Seiten rückgängig machen <strong>bestätigen</strong> ',
    '<strong>Overview</strong> of all pages' => '<strong>Übersicht</strong> aller Seiten',
    '<strong>Page</strong> history' => '<strong>Seiten</strong>historie',
    '<strong>Wiki</strong> Module' => '<strong>Wiki</strong> Modul',
    'Adds a wiki to this space.' => 'Fügt diesem Space ein Wiki hinzu.',
    'Adds a wiki to your profile.' => 'Fügt deinem Profil ein Wiki hinzu.',
    'Back to page' => 'Zurück zur Seite',
    'Cancel' => 'Abbrechen',
    'Delete' => 'Löschen',
    'Do you really want to delete this page?' => 'Willst du diese Seite wirklich löschen?',
    'Do you really want to revert this page?' => 'Willst du diese Seite wirklich rückgängig machen?',
    'Edit page' => 'Seite bearbeiten',
    'Edited at' => 'Erstellt von',
    'Go back' => 'Zurück zur Historie',
    'Invalid character in page title!' => 'Ungültige Zeichen im Seitentitel!',
    'Is homepage' => 'Als Startseite',
    'Let\'s go!' => 'Starten',
    'Main page' => 'Hauptseite',
    'New page' => 'Neue Seite',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'Noch keine Seiten erstellt. Es liegt also an dir. <br>Erstelle jetzt die erste Seite.',
    'Overview' => 'Übersicht',
    'Page History' => 'Seitenhistorie',
    'Page creation disabled!' => 'Erstellung von Seiten deaktiviert!',
    'Page not editable!' => 'Seite nicht editierbar!!',
    'Page not found.' => 'Seite nicht gefunden.',
    'Page title already in use!' => 'Seitentitel bereits vorhanden!',
    'Permalink' => 'Permalink',
    'Permission denied. You have no administration rights.' => 'Zugriff verweigert. Du hast keine Administrationsrechte.',
    'Permission denied. You have no rights to view the history.' => 'Zugriff verweigert. Du hast keine Rechte, die Historie einzusehen.',
    'Protected' => 'Geschützt',
    'Revert' => 'Rückgängig',
    'Revert not possible. Already latest revision!' => 'Rückgängig nicht möglich. Dies ist bereits die letzte Revision!',
    'Revert this' => 'Dies rückgängig machen',
    'View' => 'Ansicht',
    'Wiki' => 'Wiki',
    'You need to be member of the space "%space_name%" to access this wiki page!' => 'Um auf diese Wiki-Seite zugreifen zu können, musst du Mitglied des Space "%space_name%" sein!',
    'by' => 'von',
];
