<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Permalink' => '',
    '<strong>Confirm</strong> page deleting' => '<strong>Bestätigen</strong> Seite löschen',
    '<strong>Confirm</strong> page reverting' => '<strong>Bestätigen</strong> Seite wiederherstellen ',
    '<strong>Overview</strong> of all pages' => '<strong>Übersicht</strong> aller Seiten',
    '<strong>Page</strong> history' => '<strong>Seiten</strong> Protokoll',
    '<strong>Wiki</strong> Module' => '<strong>Wiki</strong> Module',
    'Adds a wiki to this space.' => 'Estelle ein Wiki in deinem Space.',
    'Adds a wiki to your profile.' => 'Estelle ein Wiki in deinem Profil.',
    'Back to page' => 'Zurück zur Seite',
    'Cancel' => 'Abbrechen',
    'Delete' => 'Löschen',
    'Do you really want to delete this page?' => 'Willst du diese Seite wirklich löschen?',
    'Do you really want to revert this page?' => 'Willst du diese Seite wirklich wiederherstellen?',
    'Edit page' => 'Seite bearbeiten',
    'Edited at' => 'Erstellt von',
    'Go back' => 'Geh zurück',
    'Invalid character in page title!' => 'Ungültige Zeichen im Seitentitel!',
    'Let\'s go!' => 'Starten',
    'Main page' => 'Hauptseite',
    'New page' => 'Neue Seite',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'Noch keine Seiten erstellt. Es liegt an dir die erste Seite zu <br>erstellen!',
    'Overview' => 'Übersicht',
    'Page History' => 'Seiten Protokoll ',
    'Page title already in use!' => 'Seiten Titel bereits vorhanden!',
    'Revert' => 'Zurückkehren',
    'Revert this' => 'Zurückkehren zu',
    'View' => 'Vorschau',
    'Wiki' => 'Wiki',
    'by' => 'von',
];
