<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Overview</strong>' => '',
    'Are you really sure? All existing category page assignments will be removed!' => '',
    'Categories' => '',
    'Category' => '',
    'Invalid category!' => '',
    'Is category' => '',
    'Is homepage' => '',
    'Page creation disabled!' => '',
    'Page list' => '',
    'Page not editable!' => '',
    'Page not found.' => '',
    'Pages in this category' => '',
    'Pages without category' => '',
    'Permission denied. You have no administration rights.' => '',
    'Permission denied. You have no rights to view the history.' => '',
    'Protected' => '',
    'Revert not possible. Already latest revision!' => '',
    'Show all {count} pages.' => '',
    'You need to be member of the space "%space_name%" to access this wiki page!' => '',
    '<strong>Confirm</strong> page deleting' => '<strong>تایید</strong> حذف صفحه',
    '<strong>Confirm</strong> page reverting' => '<strong>تایید</strong> برگرداندن صفحه',
    '<strong>Overview</strong> of all pages' => '<strong>مرور</strong> همه‌ی صفحه‌ها',
    '<strong>Page</strong> history' => 'تاریخچه‌ی <strong>صفحه</strong> ',
    '<strong>Wiki</strong> Module' => 'ماژول <strong>ویکی</strong>',
    'Adds a wiki to this space.' => 'یک ویکی به این صفحه اضافه‌می‌کند.',
    'Adds a wiki to your profile.' => 'یک ویکی به این پروفایل اضافه‌می‌کند.',
    'Back to page' => 'بازگشت به صفحه',
    'Cancel' => 'انصراف',
    'Delete' => 'حذف',
    'Do you really want to delete this page?' => 'آیا واقعا می‌خواهید این صفحه را حذف کنید؟',
    'Do you really want to revert this page?' => 'آیا واقعا می‌خواهید این صفحه را برگردانید؟',
    'Edit page' => 'ویرایش صفحه',
    'Edited at' => 'ویرایش شده در',
    'Go back' => 'بازگشت',
    'Invalid character in page title!' => 'کاراکتر نامعتبر در عنوان صفحه!',
    'Let\'s go!' => 'برویم!',
    'Main page' => 'صفحه‌ی اصلی',
    'New page' => 'صفحه‌ی جدید',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'هنوز هیچ صفحه‌ای ساخته‌نشده‌است. بنابراین بر عهده‌ی شماست. <br> اولین صفحه‌ را الان بسازید.',
    'Overview' => 'بررسی اجمالی',
    'Page History' => 'تاریخچه‌ی صفحه',
    'Page title already in use!' => 'عنوان صفحه در حال استفاده‌شدن است!',
    'Permalink' => 'پرمالينك',
    'Revert' => 'برگرداندن',
    'Revert this' => 'برگرداندن این',
    'View' => 'نمایش',
    'Wiki' => 'ویکی',
    'by' => 'توسط',
];
