<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Overview</strong>' => '',
    'Are you really sure? All existing category page assignments will be removed!' => '',
    'Categories' => '',
    'Category' => '',
    'Invalid category!' => '',
    'Is category' => '',
    'Page list' => '',
    'Pages in this category' => '',
    'Pages without category' => '',
    'Show all {count} pages.' => '',
    '<strong>Confirm</strong> page deleting' => '<strong>Bekreft</strong> sletting av side
',
    '<strong>Confirm</strong> page reverting' => '<strong>Bekreft</strong> tilbakestilling av side',
    '<strong>Overview</strong> of all pages' => '<strong>Oversikt</strong> over alle sider',
    '<strong>Page</strong> history' => '<strong>Sidehistorikk</strong>',
    '<strong>Wiki</strong> Module' => '<strong>Wiki-modul</strong>',
    'Adds a wiki to this space.' => 'Legger til et wiki i denne gruppen',
    'Adds a wiki to your profile.' => 'Legger til et wiki på din profil',
    'Back to page' => 'Tilbake til side',
    'Cancel' => 'Avbryt',
    'Delete' => 'Slett',
    'Do you really want to delete this page?' => 'Vil du virkelig slette denne siden?',
    'Do you really want to revert this page?' => 'Vil du virkelig tilbakestille denne siden?',
    'Edit page' => 'Rediger side',
    'Edited at' => 'Redigert',
    'Go back' => 'Gå tilbake',
    'Invalid character in page title!' => 'Ugyldig tegn i sidetittel!',
    'Is homepage' => 'Er hovedside',
    'Let\'s go!' => 'Kom igjen!',
    'Main page' => 'Hovedside',
    'New page' => 'Ny side',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'Ingen sider opprettet enda. Lag den første siden nå!',
    'Overview' => 'Oversikt',
    'Page History' => 'Sidehistorikk',
    'Page creation disabled!' => 'Opprettelse av sider er deaktivert!',
    'Page not editable!' => 'Siden kan ikke redigeres!',
    'Page not found.' => 'Siden ikke funnet.',
    'Page title already in use!' => 'Sidetittel allerede i bruk!',
    'Permalink' => 'Permalink',
    'Permission denied. You have no administration rights.' => 'Ikke tillatt! Du har ikke administratorrettigheter.',
    'Permission denied. You have no rights to view the history.' => 'Ikke tillatt! Du har ingen rettigheter til å se historikken.',
    'Protected' => 'Beskyttet',
    'Revert' => 'Tilbakestill',
    'Revert not possible. Already latest revision!' => 'Tilbakestilling ikke mulig, allerede siste revisjon!',
    'Revert this' => 'Tilbakestill denne',
    'View' => 'Visning',
    'Wiki' => 'Wiki',
    'You need to be member of the space "%space_name%" to access this wiki page!' => 'Du må være medlem av gruppen "%space_name%" for å se denne wikisiden!',
    'by' => 'av',
];
