<?php


namespace humhub\modules\wiki\widgets;


use humhub\widgets\Button;
use humhub\widgets\Modal;
use humhub\widgets\ModalButton;
use Yii;

class WikiLinkModal extends Modal
{
    public $id = 'wikiLinkModal';

    public function init()
    {
        $this->header = Yii::t('WikiModule.base', '<strong>Set</strong> wiki link');
        $this->body = $this->render('wikiLinkModal');
        $this->footer = Button::save()->action('wiki.setEditorLink').ModalButton::cancel();
        parent::init(); // TODO: Change the autogenerated stub
    }

}