<?php


namespace humhub\modules\wiki\widgets;


use humhub\modules\content\widgets\richtext\ProsemirrorRichTextEditor;
use humhub\modules\content\widgets\richtext\RichText;
use Yii;

class WikiEditor extends ProsemirrorRichTextEditor
{
    public $preset = 'wiki';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->placeholder = Yii::t('WikiModule.base', 'Page content');
    }

    public static  $renderer = [
        'class' => WikiRichText::class
    ];

}