<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Is homepage' => '',
    'Page creation disabled!' => '',
    'Page not editable!' => '',
    'Page not found.' => '',
    'Permalink' => '',
    'Permission denied. You have no administration rights.' => '',
    'Permission denied. You have no rights to view the history.' => '',
    'Protected' => '',
    'Revert not possible. Already latest revision!' => '',
    'You need to be member of the space "%space_name%" to access this wiki page!' => '',
    '<strong>Confirm</strong> page deleting' => '<strong>تأكيد</strong> رغبتك في حذف الصفحة',
    '<strong>Confirm</strong> page reverting' => '<strong>تأكيد</strong> رغبتك في إعادة الصفحة لنسخة سابقة',
    '<strong>Overview</strong> of all pages' => '<strong>نظرة شاملة</strong> على كل الصفحات',
    '<strong>Page</strong> history' => 'تاريخ الصفحة',
    '<strong>Wiki</strong> Module' => 'موديول نظام ويكي',
    'Adds a wiki to this space.' => 'يضيف موسوعة ويكي لهذه الباحة',
    'Adds a wiki to your profile.' => 'يضيف موسوعة ويكي لصفحتك الشخصية',
    'Back to page' => 'عودة للصفحة',
    'Cancel' => 'إلغاء',
    'Delete' => 'حذف',
    'Do you really want to delete this page?' => 'هل أنت متأكد من رغبتك في حذف هذه الصفحة؟ ',
    'Do you really want to revert this page?' => 'هل أنت متأكد من رغبتك في إعادة هذه الصفحة إلى نسخة سابقة؟',
    'Edit page' => 'تعديل الصفحة',
    'Edited at' => 'تم التعديل في',
    'Go back' => 'عودة',
    'Invalid character in page title!' => 'حرف خاطيء في عنوان الصفحة!',
    'Let\'s go!' => 'فلننطلق!',
    'Main page' => 'الصفحة الرئيسية',
    'New page' => 'صفحة جديدة',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'لا توجد صفحات بعدـ الأمر منوط بك. <br> إبدأ بكتابة أول صفحة الآن.',
    'Overview' => 'نظرة شاملة',
    'Page History' => 'تاريخ التعديلات',
    'Page title already in use!' => 'هذا العنوان مستعمل مسبقاً!',
    'Revert' => 'استعادة نسخة سابقة',
    'Revert this' => 'إستعادة هذه الصفحة',
    'View' => 'عرض',
    'Wiki' => 'ويكي',
    'by' => 'بواسطة',
];
