<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Overview</strong>' => '',
    'Are you really sure? All existing category page assignments will be removed!' => '',
    'Categories' => '',
    'Category' => '',
    'Invalid category!' => '',
    'Is category' => '',
    'Page list' => '',
    'Pages in this category' => '',
    'Pages without category' => '',
    'Show all {count} pages.' => '',
    '<strong>Confirm</strong> page deleting' => '<strong>Xác nhận</strong> xóa trang',
    '<strong>Confirm</strong> page reverting' => '<strong>Xác nhận</strong> hoàn trả lại trang',
    '<strong>Overview</strong> of all pages' => '<strong>Tổng quan</strong> tất cả các trang',
    '<strong>Page</strong> history' => 'Lịch sử <strong>Trang</strong>',
    '<strong>Wiki</strong> Module' => 'Module <strong>Kiến thức</strong>',
    'Adds a wiki to this space.' => 'Thêm module Kiến thức vào phòng làm việc này.',
    'Adds a wiki to your profile.' => 'Thêm module Kiến thức vào trang cá nhân của bạn',
    'Back to page' => 'Quay trở lại trang',
    'Cancel' => 'Hủy',
    'Delete' => 'Xóa',
    'Do you really want to delete this page?' => 'Bạn thực sự muốn xóa trang này?',
    'Do you really want to revert this page?' => 'Bạn thực sự muốn hoàn trả lại trang này?',
    'Edit page' => 'Chỉnh sửa trang',
    'Edited at' => 'Đã chỉnh sửa vào',
    'Go back' => 'Quay lại',
    'Invalid character in page title!' => 'Ký tự không hợp lệ ở tiêu đề trang!',
    'Is homepage' => 'Là trang chủ',
    'Let\'s go!' => 'Triển khai thôi!',
    'Main page' => 'Trang chính',
    'New page' => 'Trang mới',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'Chưa có trang nào được tạo. Hãy <br>Là người tạo trang đầu tiên.
',
    'Overview' => 'Tổng quan',
    'Page History' => 'Lịch sử trang',
    'Page creation disabled!' => 'Tạo trang đã bị vô hiệu hóa!',
    'Page not editable!' => 'Trang không thể chỉnh sửa!',
    'Page not found.' => 'Không tìm thấy trang.',
    'Page title already in use!' => 'Tiêu đề trang đã tồn tại!',
    'Permalink' => 'Liên kết tĩnh',
    'Permission denied. You have no administration rights.' => 'Từ chối truy cập. Bạn phải có quyền quản trị.',
    'Permission denied. You have no rights to view the history.' => 'Từ chối truy cập. Bạn không có quyền xem lịch sử trang.',
    'Protected' => 'Được bảo vệ',
    'Revert' => 'Hoàn trả lại',
    'Revert not possible. Already latest revision!' => 'Không có khả năng hoàn trả lại. Đây là bản sửa đổi mới nhất!',
    'Revert this' => 'Hoàn trả lại bản này',
    'View' => 'Xem',
    'Wiki' => 'Kiến thức',
    'You need to be member of the space "%space_name%" to access this wiki page!' => 'Bạn cần là thành viên của phòng làm việc "%space_name%"  để truy cập trang kiến thức này!',
    'by' => 'bởi',
];
