<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Overview</strong>' => '',
    'Are you really sure? All existing category page assignments will be removed!' => '',
    'Categories' => '',
    'Category' => '',
    'Invalid category!' => '',
    'Is category' => '',
    'Is homepage' => '',
    'Page creation disabled!' => '',
    'Page list' => '',
    'Page not editable!' => '',
    'Page not found.' => '',
    'Pages in this category' => '',
    'Pages without category' => '',
    'Permission denied. You have no administration rights.' => '',
    'Permission denied. You have no rights to view the history.' => '',
    'Protected' => '',
    'Revert not possible. Already latest revision!' => '',
    'Show all {count} pages.' => '',
    'You need to be member of the space "%space_name%" to access this wiki page!' => '',
    '<strong>Confirm</strong> page deleting' => '<strong>Potwierdź</strong> usunięcie strony',
    '<strong>Confirm</strong> page reverting' => '<strong>Potwierdź</strong> przywrócenie strony',
    '<strong>Overview</strong> of all pages' => '<strong>Podsumowanie</strong> wszystkich stron',
    '<strong>Page</strong> history' => 'Historia <strong>strony</strong>',
    '<strong>Wiki</strong> Module' => 'Moduł <strong>Wiki</strong>',
    'Adds a wiki to this space.' => 'Dodaje wiki do tej strefy.',
    'Adds a wiki to your profile.' => 'Dodaje wiki do Twojego profilu.',
    'Back to page' => 'Powrót do strony',
    'Cancel' => 'Anuluj',
    'Delete' => 'Usuń',
    'Do you really want to delete this page?' => 'Czy na pewno usunąć stronę?',
    'Do you really want to revert this page?' => 'Czy na pewno przywrócić stronę?',
    'Edit page' => 'Edytuj stronę',
    'Edited at' => 'Edytowano',
    'Go back' => 'Powrót',
    'Invalid character in page title!' => 'Nieprawidłowy znak w tytule strony!',
    'Let\'s go!' => 'Jedziemy!',
    'Main page' => 'Strona główna',
    'New page' => 'Nowa strona',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'Brak utworzonych stron. Wszystko zależy od Ciebie.<br>Utwórz nową stronę teraz.',
    'Overview' => 'Przegląd',
    'Page History' => 'Historia strony',
    'Page title already in use!' => 'Tytuł strony jest już zajęty!',
    'Permalink' => 'Odnośnik',
    'Revert' => 'Przywróć',
    'Revert this' => 'Przywróć to',
    'View' => 'Widok',
    'Wiki' => 'Wiki',
    'by' => 'przez',
];
