<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Overview</strong>' => '',
    'Adds a wiki to this space.' => '',
    'Adds a wiki to your profile.' => '',
    'Are you really sure? All existing category page assignments will be removed!' => '',
    'Categories' => '',
    'Category' => '',
    'Do you really want to delete this page?' => '',
    'Do you really want to revert this page?' => '',
    'Invalid category!' => '',
    'Invalid character in page title!' => '',
    'Is category' => '',
    'Main page' => '',
    'Page creation disabled!' => '',
    'Page list' => '',
    'Page not editable!' => '',
    'Page not found.' => '',
    'Pages in this category' => '',
    'Pages without category' => '',
    'Permission denied. You have no administration rights.' => '',
    'Permission denied. You have no rights to view the history.' => '',
    'Show all {count} pages.' => '',
    'View' => '',
    'Wiki' => '',
    'You need to be member of the space "%space_name%" to access this wiki page!' => '',
    'by' => '',
    '<strong>Confirm</strong> page deleting' => 'Biztosan <strong>törli</strong> az oldalt?',
    '<strong>Confirm</strong> page reverting' => 'Biztosan <strong>visszaállítja</strong> az oldalt?',
    '<strong>Overview</strong> of all pages' => '<strong>Oldalak</strong> listája',
    '<strong>Page</strong> history' => '<strong>Korábbi</strong> változatok',
    '<strong>Wiki</strong> Module' => '<strong>Wiki</strong> modul',
    'Back to page' => 'Vissza az oldalhoz',
    'Cancel' => 'Mégsem',
    'Delete' => 'Törlés',
    'Edit page' => 'Oldal szerkesztése',
    'Edited at' => 'Szerkesztve',
    'Go back' => 'Vissza',
    'Is homepage' => 'Ez legyen a kezdőoldal',
    'Let\'s go!' => 'Gyerünk!',
    'New page' => 'Új oldal',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'Még nincs itt egy oldal sem, úgyhogy rajtad a sor.<br>Hozz létre egyet!',
    'Overview' => 'Tartalomjegyzék',
    'Page History' => 'Korábbi változatok',
    'Page title already in use!' => 'Már van ilyen című oldal!',
    'Permalink' => 'Tartalom linkje',
    'Protected' => 'Védett',
    'Revert' => 'Visszaállás',
    'Revert not possible. Already latest revision!' => 'Nem lehet visszaállni. Ez az aktuális változat.',
    'Revert this' => 'Visszaállás erre',
];
