<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Permalink' => '',
    '<strong>Confirm</strong> page deleting' => '<strong>Bekræft</strong> side sletning',
    '<strong>Confirm</strong> page reverting' => '<strong>Bekræft</strong> side nulstilling',
    '<strong>Overview</strong> of all pages' => '<strong>Oversigt</strong> over alle sider',
    '<strong>Page</strong> history' => '<strong>Side</strong> historik',
    '<strong>Wiki</strong> Module' => '<strong>Wiki</strong> Modul',
    'Adds a wiki to this space.' => 'Tilføjet et wiki til denne side',
    'Adds a wiki to your profile.' => 'Tilføjet et wiki til din profil',
    'Back to page' => 'Tilbage til side',
    'Cancel' => 'Afbryd',
    'Delete' => 'Slet',
    'Do you really want to delete this page?' => 'Vil du virkelig slette denne side?',
    'Do you really want to revert this page?' => 'Vil du virkelig nulstille denne side?',
    'Edit page' => 'Rediger side',
    'Edited at' => 'Redigeret den',
    'Go back' => 'Gå tilbage',
    'Invalid character in page title!' => 'Ugyldigt tegn i sidetitel!',
    'Let\'s go!' => 'Let\'s go!',
    'Main page' => 'Forside',
    'New page' => 'Ny side',
    'No pages created yet.  So it\'s on you.<br>Create the first page now.' => 'Ingen oprettede sider endnu. So det er op til dig.<br>opret en først.',
    'Overview' => 'Oversigt',
    'Page History' => 'Side historik',
    'Page title already in use!' => 'Side titel er allerede i brug!',
    'Revert' => 'Nulstil',
    'Revert this' => 'Nulstil denne',
    'View' => 'Se',
    'Wiki' => 'Wiki',
    'by' => 'af',
];
